// flow-typed signature: a0e44844677bc6361d9effdb8b05438f
// flow-typed version: <<STUB>>/vega_v3.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega/bin/lcg' {
  declare module.exports: any;
}

declare module 'vega/build/vega-core' {
  declare module.exports: any;
}

declare module 'vega/build/vega-core.min' {
  declare module.exports: any;
}

declare module 'vega/build/vega' {
  declare module.exports: any;
}

declare module 'vega/build/vega.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega/bin/lcg.js' {
  declare module.exports: $Exports<'vega/bin/lcg'>;
}
declare module 'vega/build/vega-core.js' {
  declare module.exports: $Exports<'vega/build/vega-core'>;
}
declare module 'vega/build/vega-core.min.js' {
  declare module.exports: $Exports<'vega/build/vega-core.min'>;
}
declare module 'vega/build/vega.js' {
  declare module.exports: $Exports<'vega/build/vega'>;
}
declare module 'vega/build/vega.min.js' {
  declare module.exports: $Exports<'vega/build/vega.min'>;
}
declare module 'vega/index' {
  declare module.exports: $Exports<'vega'>;
}
declare module 'vega/index.js' {
  declare module.exports: $Exports<'vega'>;
}
