// flow-typed signature: 7d2a5412e48abc92a4429f25018fe461
// flow-typed version: <<STUB>>/vega-embed_v3.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-embed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-embed' {
  declare module.exports: any;
}
