// flow-typed signature: 01f93761317a434f4b800bbf0bf74b7d
// flow-typed version: <<STUB>>/vega-tooltip_v3.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-tooltip' {
  declare module.exports: any;
}
